name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3  # Mettez à jour vers v3

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Mettez à jour vers v3
      with:
        node-version: '22.5'  # Mettez à jour vers la dernière version stable (ou '16' si nécessaire)

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
