name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js (v20.x)
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Mettez à jour ici avec une version >=20.8.1

      - name: Install dependencies
        run: npm install

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_CUSTOM }}
        run: npx semantic-release
